using System.Data;
using System.Diagnostics;
using System.Runtime.InteropServices;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Skyrim;
using Mutagen.Bethesda.Synthesis;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using Noggog;
using WeaponKeywords.Types;

namespace WeaponKeywords;
public class Program
{
    static Lazy<Database> LazyDB = new();
    static Database DB => LazyDB.Value;
    public static async Task<int> Main(string[] args)
    {
        return await SynthesisPipeline.Instance
            .SetAutogeneratedSettings("Database", "database.json", out LazyDB)
            .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
            .AddRunnabilityCheck(ConvertJson)
            .SetTypicalOpen(GameRelease.SkyrimSE, "SynWeaponKeywords.esp")
            .Run(args);
    }
    public static void ConvertJson(IRunnabilityState state)
    {
        var inf = new ProcessStartInfo
        {
            CreateNoWindow = true,
            WorkingDirectory = state.ExtraSettingsDataPath,
            RedirectStandardInput = true,
            RedirectStandardError = true,
            RedirectStandardOutput = true,
            FileName = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "jd" : "jd.exe",
            Arguments = "-o database.json -p patch.json database.json"
        };
        JObject? DBConv = new();
        if (File.Exists(Path.Combine(state.ExtraSettingsDataPath!, "database.bak.json")))
        {
            File.Delete(Path.Combine(state.ExtraSettingsDataPath!, "database.json"));
            File.Move(Path.Combine(state.ExtraSettingsDataPath!, "database.bak.json"), Path.Combine(state.ExtraSettingsDataPath!, "database.json"));
        }
        if (File.Exists(Path.Combine(state.ExtraSettingsDataPath!, "database.json")))
        {
            DBConv = JObject.Parse(File.ReadAllText(Path.Combine(state.ExtraSettingsDataPath!, "database.json")));
        }
        if ((DBConv["DBVer"]?.Value<int>() ?? -1) < 0)
        {
            DBConv = new()
            {
                ["DBVer"] = 0,
                ["DoUpdates"] = true,
                ["UpdateLocation"] = DBConst.DEFAULT_UPDATE_LOCATION,
            };
            File.WriteAllText(Path.Combine(state.ExtraSettingsDataPath!, "database.json"), DBConv.ToString(Formatting.Indented));
        }
        if (DBConv["DoUpdates"]?.Value<bool>() ?? true)
        {
            using var HttpClient = new HttpClient();
            HttpClient.Timeout = TimeSpan.FromSeconds(5);
            string resp = string.Empty;
            try
            {
                var http = HttpClient.GetStringAsync(DBConv["UpdateLocation"]?.Value<string>() ?? DBConst.DEFAULT_UPDATE_LOCATION);
                http.Wait();
                resp = http.Result;
            }
            catch (Exception)
            {
                Console.WriteLine("Failed to download patch index");
                return;
            }
            if (!File.Exists(Path.Combine(state.ExtraSettingsDataPath!, "jd.exe")))
            {
                Console.Out.WriteLine("Downloading the latest release of JD for DB patching");
                var task = HttpClient.GetByteArrayAsync("https://github.com/josephburnett/jd/releases/latest/download/jd-amd64-windows.exe");
                task.Wait();
                File.WriteAllBytes(Path.Combine(state.ExtraSettingsDataPath!, "jd.exe"), task.Result);
            }
            var pi = JArray.Parse(resp).ToObject<List<string>>()!;
            for (int i = DBConv["DBVer"]!.Value<int>(); i < pi.Count; i++)
            {
                try
                {
                    Console.WriteLine($"Downloading patch {pi[i]}");
                    var http = HttpClient.GetStringAsync(pi[i]);
                    http.Wait();
                    resp = http.Result;
                }
                catch (Exception)
                {
                    Console.WriteLine($"Failed to download patch {pi[i]}");
                    return;
                }
                File.WriteAllText(Path.Combine(state.ExtraSettingsDataPath!, "patch.json"), resp);
                Process.Start(inf)?.WaitForExit();
                File.Delete(Path.Combine(state.ExtraSettingsDataPath!, "patch.json"));
            }
        }
        File.Copy(Path.Combine(state.ExtraSettingsDataPath!, "database.json"), Path.Combine(state.ExtraSettingsDataPath!, "database.bak.json"));
        var SWK_PATCHES = state.DataFolderPath.EnumerateFiles().Where(x => x.NameWithoutExtension.EndsWith("_SWK"));
        foreach (var patch in SWK_PATCHES)
        {
            Console.WriteLine($"Applying data-patch {patch.NameWithoutExtension}");
            File.Copy(patch.Path, Path.Combine(state.ExtraSettingsDataPath!, "patch.json"));
            Process.Start(inf)?.WaitForExit();
            File.Delete(Path.Combine(state.ExtraSettingsDataPath!, "patch.json"));
        }

    }
    public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state)
    {
        Console.WriteLine($"Running with Database Version: V{DB.DBVer}");
        Dictionary<string, List<IKeywordGetter>> formkeys = new();
        var Keywords = DB.DB.SelectMany(x => x.Value.keyword).Distinct();
        foreach (var kyd in DB.DB.Select(x => x.Key))
        {
            formkeys[kyd] = new List<IKeywordGetter>();
        }
        foreach (var src in DB.sources)
        {
            if (!state.LoadOrder.PriorityOrder.Select(x => x.ModKey).Contains(src)) continue;
            state.LoadOrder.TryGetValue(src, out var mod);
            if (mod != null && mod.Mod != null && mod.Mod.Keywords != null)
            {
                var keywords = mod.Mod.Keywords
                    .Where(x => Keywords.Contains(x.EditorID ?? ""))
                    .ToList() ?? new List<IKeywordGetter>();
                foreach (var keyword in keywords)
                {
                    if (keyword == null) continue;
                    var type = DB.DB.Where(x => x.Value.keyword.Contains(keyword.EditorID ?? "")).Select(x => x.Key);
                    Console.WriteLine($"Keyword : {keyword.FormKey.IDString()}:{keyword.FormKey.ModKey}:{keyword.EditorID}");
                    foreach (var tp in type)
                    {
                        formkeys[tp].Add(keyword);
                    }
                }
            }
        }
        foreach (var weapon in state.LoadOrder.PriorityOrder.Weapon().WinningOverrides())
        {
            if (!weapon.Template.IsNull) continue;
            var edid = weapon.EditorID;
            var matchingKeywords = DB.DB
                .Where(kv => kv.Value.commonNames.Any(cn => weapon.Name?.String?.Contains(cn, StringComparison.OrdinalIgnoreCase) ?? false))
                .Where(kv => kv.Value.validEquipType == DBConst.equipTable[weapon.EquipmentType.FormKey])
                .Where(kv => !kv.Value.excludeNames.Any(en => weapon.Name?.String?.Contains(en, StringComparison.OrdinalIgnoreCase) ?? false))
                .Where(kv => !kv.Value.exclude.Contains(weapon.FormKey))
                .Where(kv => !DB.excludes.phrases.Any(ph => weapon.Name?.String?.Contains(ph, StringComparison.OrdinalIgnoreCase) ?? false))
                .Where(kv => !DB.excludes.weapons.Contains(weapon.FormKey))
                .Select(kv => kv.Key)
                .Concat(DB.DB.Where(x => x.Value.include.Contains(weapon.FormKey)).Select(x => x.Key))
                .Distinct()
                .ToHashSet();

            IWeapon? nw = null;
            if (matchingKeywords.Count > 0)
            {
                Console.WriteLine($"{edid} - {weapon.FormKey.IDString()}:{weapon.FormKey.ModKey} matches: {string.Join(",", matchingKeywords)}");
                Console.WriteLine($"\t{weapon.Name}: {weapon.EditorID} is {string.Join(" & ", DB.DB.Where(x => matchingKeywords.Contains(x.Key)).Select(x => x.Value.outputDescription))}");
                var keywords = weapon.Keywords?
                    .Select(x => x.TryResolve(state.LinkCache, out var kyd) ? kyd : null)
                    .Where(x => x != null)
                    .Concat(matchingKeywords.SelectMany(x => formkeys[x]))
                    .Select(x => x!)
                    .DistinctBy(x => x.FormKey)
                    .ToHashSet() ?? new();

                if (keywords.Any(x => !(weapon.Keywords?.Contains(x) ?? false)))
                {
                    nw = nw == null ? state.PatchMod.Weapons.GetOrAddAsOverride(weapon)! : nw!;
                    nw.Keywords = keywords.Select(x => x.ToLinkGetter()).ToExtendedList();
                    Console.WriteLine($"\tSetting keywords to:\n\t\t{string.Join("\n\t\t", keywords.Select(x => $"{x.EditorID} from {x.FormKey.ModKey}"))}");
                }
                var fKeyword = matchingKeywords.First();
            }
        }
    }
}